name: Run test

on: [workflow_dispatch]

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Install project dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --reporter mocha-allure-reporter --reporter-options allureResultsPath=allure-results

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-reports

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-reports
          path: allure-reports

      - name: Upload Cypress screenshots and videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots/
            cypress/videos/
